#ifndef FLUID_FFI_H
#define FLUID_FFI_H

/* Generated by cbindgen from crates/fluid-ffi/src/lib.rs. Do not edit; scripts/gate.sh rejects drift. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * The renderer behind the C ABI: an opaque box the Swift shell drives by
 * pointer, on the main thread only.
 */
typedef struct FluidRenderer FluidRenderer;

typedef struct FluidVec3 {
  float x;
  float y;
  float z;
} FluidVec3;

typedef struct FluidRenderStats {
  uint64_t frames;
  float interval_p50_us;
  float interval_p99_us;
  float interval_max_us;
  float acquire_p50_us;
  float acquire_p99_us;
  float encode_p50_us;
  float encode_p99_us;
  float gpu_p50_us;
  float gpu_p99_us;
  float compression_avg;
  float compression_max;
  float density_min;
  float density_max;
  float pressure_min;
  float pressure_max;
  float v_max;
  float temperature_min;
  float temperature_max;
  uint32_t clamp_count;
  uint32_t neighbour_overflow;
  uint32_t substeps;
  uint64_t idle_frames;
} FluidRenderStats;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * How many fingers the sim drags with at once. A shell must give each
 * finger a slot below this and hold it for as long as that finger
 * stays on the glass.
 */
extern const uint32_t FLUID_TOUCH_SLOTS;

/**
 * Builds the renderer on a layer: `particle_count` sprites of
 * `sprite_radius` metres, or, when `bench_sweeps` is nonzero, the M3
 * stage-0 microbench at `bench_spacing` metres. A nonzero `sim_substeps`
 * runs the M3 fluid instead, at that many substeps a frame, with
 * `particle_scale` times the shipped particle count unless
 * `bench_spacing` pins the spacing. Returns null when GPU setup fails,
 * with the reason on stderr.
 *
 * # Safety
 *
 * `metal_layer` must be a `CAMetalLayer` pointer, kept alive until
 * `fluid_renderer_destroy`. Call on the main thread.
 */
struct FluidRenderer *fluid_renderer_create(void *metal_layer,
                                            uint32_t width,
                                            uint32_t height,
                                            uint32_t particle_count,
                                            float sprite_radius,
                                            uint32_t bench_sweeps,
                                            float bench_spacing,
                                            uint32_t sim_substeps,
                                            uint32_t tracers,
                                            float particle_scale);

/**
 * One frame: integrate the particles, draw them over the body-force tint,
 * present. `now_ms` is `CADisplayLink.timestamp` in milliseconds. Returns
 * 1 when a frame was stepped and presented, 0 when the settled sim slept
 * it; at 0 the shell may drop its tick rate until the next 1.
 *
 * # Safety
 *
 * `renderer` must be a live pointer from `fluid_renderer_create`.
 */
uint32_t fluid_renderer_frame(struct FluidRenderer *renderer,
                              struct FluidVec3 gravity,
                              struct FluidVec3 user_acceleration,
                              struct FluidVec3 rotation_rate,
                              double now_ms);

/**
 * Reseeds the fluid at `scale` times the shipped particle count: a
 * rebuild of the sim, off the frame path, after which a still phone's
 * water falls and settles again.
 *
 * # Safety
 *
 * `renderer` must be a live pointer from `fluid_renderer_create`.
 */
void fluid_renderer_set_particles(struct FluidRenderer *renderer, float scale);

/**
 * The particle count `fluid_renderer_set_particles` would seed at
 * `scale`, for the menu's labels.
 *
 * # Safety
 *
 * `renderer` must be a live pointer from `fluid_renderer_create`.
 */
uint32_t fluid_renderer_particles_at(const struct FluidRenderer *renderer, float scale);

/**
 * Where one finger presses, normalised over the drawable: `x` runs 0
 * to 1 left to right, `y` 0 to 1 top to bottom. Every finger down
 * drags the water it moves through and keeps the sim awake; `down`
 * false lifts one. Call it from the gesture, not the frame.
 *
 * # Safety
 *
 * `renderer` must be a live pointer from `fluid_renderer_create`.
 */
void fluid_renderer_touch(struct FluidRenderer *renderer,
                          uint32_t slot,
                          float x,
                          float y,
                          bool down);

/**
 * Liquid glass when `flat` is false. Otherwise paint on black: the
 * flat surface, or, when `particles` is also true, the particles
 * alone as discs. `particles` alone does nothing.
 *
 * `low` is the one colour when `gradient` is false. When it is true,
 * the colour runs from `low` to `high` across `lens`, between the
 * lowest and highest the frame itself holds: 0 velocity,
 * 1 acceleration, 2 pressure, 3 proximity, and anything else
 * velocity. 4 is the direction wheel, which takes its hue from which
 * way the water goes and reads no `high`. Colour components are 0 to
 * 1 as the picker shows them; the core linearises them.
 *
 * # Safety
 *
 * `renderer` must be a live pointer from `fluid_renderer_create`.
 */
void fluid_renderer_set_look(struct FluidRenderer *renderer,
                             bool flat,
                             bool particles,
                             struct FluidVec3 low,
                             bool gradient,
                             struct FluidVec3 high,
                             uint32_t lens);

/**
 * # Safety
 *
 * `renderer` must be a live pointer from `fluid_renderer_create`.
 */
void fluid_renderer_resize(struct FluidRenderer *renderer, uint32_t width, uint32_t height);

/**
 * # Safety
 *
 * `renderer` must be a live pointer from `fluid_renderer_create`.
 */
struct FluidRenderStats fluid_renderer_stats(const struct FluidRenderer *renderer);

/**
 * # Safety
 *
 * `renderer` must come from `fluid_renderer_create`; it is dead afterwards.
 */
void fluid_renderer_destroy(struct FluidRenderer *renderer);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* FLUID_FFI_H */
