#ifndef FLUID_FFI_H
#define FLUID_FFI_H

/* Generated by cbindgen from crates/fluid-ffi/src/lib.rs. Do not edit; scripts/gate.sh rejects drift. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct FluidVec3 {
  float x;
  float y;
  float z;
} FluidVec3;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Body force per unit mass, in metres per second squared, from CoreMotion's
 * `gravity` and `userAcceleration` (both in g).
 */
struct FluidVec3 fluid_body_force(struct FluidVec3 gravity, struct FluidVec3 user_acceleration);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* FLUID_FFI_H */
